---

- hosts: "{{ server_fqdn }}"
  remote_user: root
  roles:
    - stancel.install-nagios-client  

- hosts: "{{ nagios_server_fqdn }}"
  become: true
  become_method: sudo
  roles:
    - stancel.add-config-to-nagios-server


