---

- hosts: crm.processfast.com
  remote_user: root
  vars:
    #server_fqdn: "marketing.processfast.com"
    #nagios_server_fqdn: "atlprocessfast.dyndns.org"
  roles:
    - install-nagios-client  

- hosts: atlprocessfast.dyndns.org
  #remote_user: brad
  become: true
  become_method: sudo
  vars:
    #hostname: "mautic-processfast"
    #nagios_friendly_name: "ProcessFast Mautic"
    #server_fqdn: "marketing.processfast.com"
  roles:
    - add-config-to-nagios-server


